# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import typing

class PyPipelineRunner:
    r"""
    Python class wrapper for configuring and executing pipeline runs.
    """
    def __new__(cls,device = ...,dummy = ...,model_path = ...): ...
    def run_pdf(self, pdf_path:str) -> str:
        r"""
        Executes PDF inference using configured runner parameters, returning a JSON string.
        """
        ...

    def run_pdf_dict(self, pdf_path:str) -> typing.Any:
        r"""
        Executes PDF inference using configured runner parameters, returning a native Python dict.
        """
        ...

    def run_image(self, image_path:str) -> str:
        r"""
        Executes single-image inference using configured runner parameters, returning a JSON string.
        """
        ...


def scan_image(image_path,device = ...,dummy = ...,model_path = ...) -> str:
    r"""
    Scans an image file and returns a JSON string representation of `DocumentScanResult`.
    """
    ...

def scan_pdf(pdf_path,device = ...,dummy = ...,model_path = ...) -> str:
    r"""
    Scans a PDF file and returns a JSON string representation of `DocumentScanResult`.
    """
    ...

def scan_pdf_dict(pdf_path,device = ...,dummy = ...,model_path = ...) -> typing.Any:
    r"""
    Scans a PDF file and returns a native Python dictionary (`PyObject`).
    """
    ...

